#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1
expect {
 $VMTip { send -s "wget http://$localMachine_ip/Test/script/dd.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x dd.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "./dd.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "records" {}
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

PASS
