#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1
send -s "\r"
expect {
 $VMTip { send -s "apt\-get update\r" }
 timeout {FAIL;exit}
}
expect {
 "Done" { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "apt\-get install \-y ethtool \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "ethtool eth0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "ethtool \-i eth0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "ethtool \-d eth0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "ethtool \-r eth0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "ethtool \-S eth0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

PASS
