#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]
set cpu3 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1

set spawn_id $cpu1
send -s "\r"
expect {
 $HostTip { send -s "PRCID\=\`ps auxw \| grep qemu \| head \-n 1 \| cut \-d \" \" \-f 7\`\r" }
 timeout {FAIL;exit}
}
expect {
 $HostTip { send -s "cd /proc/\$PRCID/ \r" }
 timeout {FAIL;exit}
}
set timeout 30
expect {
 $HostTip { send -s "ls \-la \r" }
 timeout {FAIL;exit}
}
expect {
 "fd" { PASS }
 timeout {FAIL;exit}
}
