#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1
send -s "\r"
expect {
 $VMTip { send -s "wget http://$localMachine_ip/Test/binary/hdparm\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x hdparm\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 1 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 2 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 3 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 4 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "./hdparm \-Tt /dev/vda\r"}
 timeout {FAIL;exit}
}
expect {
 "Timing" {}
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

PASS
