#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]
set cpu3 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1

set spawn_id $cpu1
send -s "\r"
expect {
 $HostTip { send -s "echo \"c\" \> /proc/sysrq\-trigger\r" }
 timeout {FAIL}
}
expect {
  "Kernel panic" {PASS}
  timeout {FAIL}
}
