#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1
expect {
 $VMTip { send -s "/sbin/shutdown -h now\r"}
 timeout {FAIL}
}
expect {
 "command not found" {FAIL}
 $HostTip {PASS}
 timeout {FAIL}
}
puts "END"
