#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_LOCAL ]
set cpu2 [ LOGIN_LOCAL ]
set cpu3 [ LOGIN_LOCAL ]
set cpu4 [ LOGIN_LOCAL ]

set spawn_id $cpu1
START_HOST_1

set spawn_id $cpu2
START_HOSTA_VM_1
expect {
 $VMTip { send -s "/sbin/shutdown \r"}
 timeout {FAIL}
}
expect {
 "command not found" {FAIL}
 $HostTip {}
 timeout {FAIL}
}

set spawn_id $cpu3
START_HOSTA_VM_2
expect {
 $VMTip { send -s "/sbin/shutdown \r"}
 timeout {FAIL}
}
expect {
 "command not found" {FAIL}
 $HostTip {}
 timeout {FAIL}
}

set spawn_id $cpu4
START_HOSTA_VM_3
expect {
 $VMTip { send -s "/sbin/shutdown \-h \-t 0\r"}
 timeout {FAIL}
}
expect {
 "command not found" {FAIL}
 $HostTip {PASS}
 timeout {FAIL}
}
puts "END"
