#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu2
START_HOSTA_VM_1
expect {
 $VMTip { send -s "ping 8.8.8.8\r" }
 timeout {FAIL}
}
expect {
 "64" {}
 timeout {FAIL}
}

set spawn_id $cpu1
send -s "\r"
expect {
 $HostTip { send -s "cd $vmpath\r" }
 timeout {FAIL}
}
expect {
 $HostTip { send -s "./save.sh\r" }
 timeout {FAIL}
}
expect {
 $HostTip {}
 timeout {FAIL}
}

set spawn_id $cpu2
send -s "\r"
expect {
 $HostTip { send -s "./restore.sh\r" }
 timeout {FAIL}
}

expect {
 "64" { send -s "^C";send -s "\r"}
 timeout {FAIL}
}

expect {
 $HostTip { send -s "poweroff\r" }
 timeout {FAIL}
}
expect {
 $HostTip {PASS}
 timeout {FAIL}
}
