#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu1
START_HOSTA_VM_1
send -s "\r"

expect {
 "root@vm" { send -s "wget http://$binary_ip/Test/script/dd.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x dd.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "./dd.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "records" {}
 timeout {FAIL;exit}
}

expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}
expect {
 $HostTip {PASS}
 timeout {FAIL}
}
