#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]


set spawn_id $cpu1
START_HOSTA_VM_1

set spawn_id $cpu2
puts "### CHANGE NEW TERMINAL ###"
send -s "\r"
expect {
 $HostTip {send -s "/etc/init\.d/nfs\-kernel\-server stop\r"}
 timeout {FAIL;exit}
}
expect {
 "Stopping" {}
 timeout {FAIL;exit}
}
expect {
 "OK" {}
 timeout {FAIL;exit}
}

set spawn_id $cpu1
send -s "ping 8.8.8.8\r"
#expect "64"
sleep 30

set spawn_id $cpu2
send -s "\r"
expect {
 $HostTip {send -s "/etc/init\.d/nfs\-kernel\-server restart\r"}
 timeout {FAIL;exit}
}
expect {
 "Starting" {}
 timeout {FAIL;exit}
}
expect {
 "OK" {}
 timeout {FAIL;exit}
}

set spawn_id $cpu1
send -s "^C"
send -s "\r"
expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}
expect {
 $HostTip {PASS}
 timeout {FAIL}
}
