#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu1
START_HOSTA_VM_1
send -s "\r"

expect {
 $VMTip { send -s "wget http://$binary_ip/Test/binary/iperf\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x iperf\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "./iperf \-c $hostA_ip \-w 100M \-t 120 \-i 10\r"}
 timeout {FAIL;exit}
}
expect {
 "Mbits" {}
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}


expect {
 $HostTip {PASS}
 timeout {FAIL}
}
