#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu1
START_HOSTA_VM_1
send -s "\r"

expect {
 "root@vm" { send -s "wget http://$binary_ip/Test/binary/hdparm\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x hdparm\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 0 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 1 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 2 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 3 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "mknod /dev/vda b 254 4 \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "./hdparm \-Tt /dev/vda\r"}
 timeout {FAIL;exit}
}
expect {
 "Timing" {}
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}


expect {
 $HostTip {PASS}
 timeout {FAIL}
}
