#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu1
START_HOSTA_VM_1
send -s "\r"
expect {
 $VMTip { send -s "wget http\://$binary_ip/Test/binary/crashme . \r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "chmod +x crashme\r" }
 timeout {FAIL;exit}
}
expect {
 $VMTip { send -s "\r" }
 timeout {FAIL;exit}
}

send -s "\r"
expect $VMTip {send -s "./crashme \-\+1024 666 1 00:00:10 2 \r"}

expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}
expect {
 $HostTip {PASS}
 timeout {FAIL}
}
