#!/usr/bin/expect
source configure

set cpu1 [ LOGIN_HOSTA ]
set cpu2 [ LOGIN_HOSTA ]

set spawn_id $cpu1
START_HOSTA_VM_1
send -s "\r"

set timeout 10
expect $VMTip { send -s "echo \"c\" \> /proc/sysrq\-trigger\r" }
expect {
  $VMTip { send -s "\r" }
  timeout { puts "Crash It"; exit }
}
send -s "\r"

expect {
 $VMTip { send -s "poweroff\r" }
 timeout {FAIL}
}

expect {
 $HostTip {PASS}
 timeout {FAIL}
}
