#!/usr/bin/expect
#### Basci Setting ###
set login_ip 127.0.0.1
set username root
set pwd qwer
set vmusername root
set vmpwd root
set reporter chkao
set reporter_pwd abc123
set programpath /home/tailsice/install/linaro+libvirt
set programpath2 /home/tailsice/install/migration
set jenkins_file /srv/test.tap
set localMachine_ip 192.168.101.1
set hostA_ip 192.168.101.2
set hostB_ip 192.168.101.101
set send_slow {1 .01}
#######################

proc FAIL {} {
global username
global pwd
global login_ip
global jenkins_file
spawn ssh $username@$login_ip
set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

send -s "\r"
expect $tip { puts "### FAIL ###"}
send -s "\r"
expect $tip { send -s "echo \"1..1\" \>\> $jenkins_file \r" }
expect $tip { send -s "echo \"not ok 1 It is failed\" \>\> $jenkins_file \r" }
expect $tip { exit}
}

proc PASS {} {
global username
global pwd
global login_ip
global jenkins_file
spawn ssh $username@$login_ip
set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

send -s "\r"
expect $tip { send -s "echo \"1..1\" \>\> $jenkins_file \r" }
expect $tip { send -s "echo \"ok 1 The test is pass\" \>\> $jenkins_file \r" }
expect $tip { puts "### PASS ###";exit}
}


spawn ssh $username@$login_ip

set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip 
}

set cpu1 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu2 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu3 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu4 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu5 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu6 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu7 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu8 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu9 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu10 $spawn_id

set spawn_id $cpu1

set timeout 250
send -s "cd $programpath\r"
expect {
 $tip { send -s "./start.sh\r"}
 timeout {FAIL;exit}
}
#expect { 
# "root@linaro" {}
# timeout {FAIL;exit}
#}

#puts "linaro start up!"

set spawn_id $cpu2

set timeout 250
send -s "cd $programpath2\r"
send -s "\.\/start2.sh\r"
expect {
 "root@linaro" {puts "### BOOT OK ###"}
 timeout {FAIL;exit}
}


set spawn_id $cpu3

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostA_ip\r"}
 timeout {FAIL;exit}
}

expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd \/root\/kvm\r"
expect {
 $tip { send -s "insmod \/root\/kvm\/kvm.ko\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "mount $localMachine_ip\:\/mnt\/iso \/mnt\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "chmod +x receive\_vm1.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "\.\/receive\_vm1.sh\r" }
 timeout {FAIL;exit}
}

sleep 5

set spawn_id $cpu4

send -s "\r"
expect {
  $tip {send -s "ssh $vmusername@$hostA_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd \/root\/kvm\r"
expect {
 $tip { send -s "chmod +x receive\_vm3.sh\r" }
 timeout {FAIL;exit}
}
expect { 
 $tip { send -s "\.\/receive\_vm3.sh\r" }
 timeout {FAIL;exit}
}
sleep 5

set spawn_id $cpu5

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostA_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd \/root\/kvm\r"
expect { 
 $tip { send -s "chmod +x receive\_vm4.sh\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "\.\/receive\_vm4.sh\r" }
 timeout {FAIL;exit}
}
sleep 5
set timeout 50

set spawn_id $cpu6

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd \/root\/kvm\r"
expect {
 $tip { send -s "insmod \/root\/kvm\/kvm.ko\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "mount $localMachine_ip\:\/mnt\/iso \/mnt\r" }
 timeout {FAIL;exit}
}
expect { 
 $tip { send -s "\.\/start1\-vdisk.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@vm" { send -s "echo \$HOSTNAME\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "ping $localMachine_ip \r"}
 timeout {FAIL;exit}
}
expect {
 "64" {}
 timeout {FAIL;exit}
}

set spawn_id $cpu7

send -s "\r"
expect { 
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

send -s "cd \/root\/kvm\r"
expect { 
 $tip { send -s "\.\/start3\-vdisk.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@vm" { send -s "echo \$HOSTNAME\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "vmstat 1 \r"}
 timeout {FAIL;exit}
}

set spawn_id $cpu8

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd \/root\/kvm\r"
expect {
 $tip { send -s "\.\/start4\-vdisk.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@vm" { send -s "echo \$HOSTNAME\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "top\r"}
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "top \r"}
 timeout {FAIL;exit}
}

set spawn_id $cpu9
send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
puts "### Start Migration ###"
set timeout 60
send -s "\r"
expect {
 $tip { send -s "cd \/root\/kvm\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "\.\/migrate\_vm.sh 4444 1\r"}
 timeout {FAIL;exit}
}
expect {
 "4444" { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 "qemu" { send -s "\r"}
 timeout {FAIL;exit}
}

expect {
 $tip { send -s "\.\/migrate\_vm.sh 5555 3\r"}
 timeout {FAIL;exit}
}
expect {
 "5555" { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 "qemu" { send -s "\r"}
 timeout {FAIL;exit}
}
expect { 
 $tip { send -s "\.\/migrate\_vm.sh 6666 4\r"}
 timeout {FAIL;exit}
}
expect {
 "6666" { send -s "\r" }
 timeout {FAIL;exit}
}
expect {
 "qemu" { send -s "\r"}
 timeout {FAIL;exit}
}
expect {
 $tip {}
 timeout {FAIL;exit}
}

set spawn_id $cpu3
set timeout 10
send -s "\r"
expect {
 "64" { send -s "" }
 timeout {FAIL;exit}
}
expect {
 $tip {}
 timeout {FAIL;exit}
}

set spawn_id $cpu4
set timeout 100
send -s "\r"
expect {
 "procs" { send -s "" }
 timeout {FAIL;exit}
}
#expect {
# $tip {}
# timeout {FAIL;exit}
#}

set spawn_id $cpu5
set timeout 10
send -s "\r"
expect {
 "root" {}
 timeout {FAIL;exit}
}
PASS
puts "End Program"
