#!/usr/bin/expect
#### Basci Setting ###
set login_ip 127.0.0.1
set username root
set pwd kvmarm
set vmusername root
set vmpwd root
set programpath /home/hypervisor/kvm
set programpath2 /home/hypervisor/kvm2
set localMachine_ip 192.168.20.1
set hostA_ip 192.168.20.100
set hostB_ip 192.168.20.101
set jenkins_path /var/lib/jenkins/jobs/TestRun/workspace
set vmA_ip 192.168.20.2
set send_slow {1 .01}
######################

set jenkins_file [lindex $argv 0]

proc FAIL {} {
global username
global pwd
global login_ip
global jenkins_path
global jenkins_file
spawn ssh $username@$login_ip
set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "\r"
expect $tip { puts "##FAIL##"}
#send -s "\r"
#expect $tip { send -s "echo \"1..1\" \>\> $jenkins_path/$jenkins_file \r" }
#expect $tip { send -s "echo \"not ok 1 It is failed\" \>\> $jenkins_path/$jenkins_file \r" }
#expect $tip {puts "FAIL END"}
}

proc PASS {} {
global username
global pwd
global login_ip
global jenkins_path
global jenkins_file
spawn ssh $username@$login_ip
set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "\r"
expect $tip { puts "##PASS##"}
}

spawn ssh $username@$login_ip

set tip "#"
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip 
}

set cpu1 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu2 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu3 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu4 $spawn_id

spawn ssh $username@$login_ip
set timeout 10
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$pwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}

set cpu5 $spawn_id

set spawn_id $cpu1

set timeout 250
send -s "cd $programpath2\r"
expect {
 $tip { send -s "./start2.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@linaro" {puts "### BOOT OK ###"}
 timeout {FAIL;exit}
}

set spawn_id $cpu2

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd /root/kvm\r"
expect {
 $tip { send -s "insmod /root/kvm/kvm.ko\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "mount $localMachine_ip\:\/mnt\/iso \/mnt\r" }
 timeout {FAIL;exit}
}
expect { 
 $tip { send -s "./start1\-vdisk.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@vm" { send -s "echo \$HOSTNAME\r"; set tip "root@vm" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "mount /dev/pts\r"}
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "/etc/init.d/ssh start\r"}
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "\r"; set tip "#" }
 timeout {FAIL;exit}
}
send -s "\r"
expect {
 $tip { send -s "wget http://$localMachine_ip/Test/memtest \r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "chmod \+x memtest\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "./memtest & \r" }
 timeout {FAIL;exit}
}
expect {
 $tip {puts "### Run MEMTEST ###" }
 timeout {FAIL;exit}
}

set spawn_id $cpu3

send -s "\r"
expect {
 $tip {send -s "ssh $vmusername@$hostB_ip\r"}
 timeout {FAIL;exit}
}
expect {
  -ex "(yes/no)?" {send -s "yes\r"; exp_continue}
  "assword:"     {send -s "$vmpwd\r"; exp_continue}
  "No route to host"      {exit; exp_continue}
  timeout         {send_user "connect fail\r"; exit}
  -ex $tip
}
send -s "cd /root/kvm\r"
expect { 
 $tip { send -s "./start3\-vdisk.sh\r"}
 timeout {FAIL;exit}
}
expect {
 "root@vm" { send -s "echo \$HOSTNAME\r"; set tip "root@vm" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "mount /dev/pts\r"}
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "/etc/init.d/ssh start\r"}
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "\r"; set tip "#" }
 timeout {FAIL;exit}
}
send -s "\r"
expect {
 $tip { send -s "wget http://$localMachine_ip/Test/memtest \r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "chmod \+x memtest\r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "./memtest & \r" }
 timeout {FAIL;exit}
}
expect {
 $tip {puts "### Run MEMTEST ###" }
 timeout {FAIL;exit}
}

set spawn_id $cpu1
send -s "\r"
expect {
 $tip { send -s "wget http://$localMachine_ip/Test/file\_transfer.sh \r" }
 timeout {FAIL;exit}
}
expect {
 $tip { send -s "chmod \+x file\_transfer.sh\r"}
 timeout {FAIL;exit}
}
set timeout 1000
expect {
 $tip { send -s "./file\_transfer.sh 10 4\r"; puts "RUN FILE TRANSFER ###"}
 timeout {FAIL;exit}
}
expect {
 "END" { PASS}
 timeout {FAIL;exit}
}
